.git
.github
node_modules
build
dist
coverage
npm-debug.log

.idea
.vscode
*.iml
.DS_Store

*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.eslintcache
.cache


.env
.env.*
!.env.production


playwright-report
test-results
cypress/videos
cypress/screenshots
e2e

README.md
docs
docker-compose*.yml
